name: task_manager_app
description: A CRUD Task Manager App in Flutter
version: 1.0.0+1

environment:
  sdk: '>=3.7.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2
  equatable: ^2.0.5
  sqflite: ^2.2.8+4
  path: ^1.8.3
  http: ^1.1.0
  dio: ^5.3.2
  get_it: ^7.6.0
  intl: ^0.18.1
  connectivity_plus: ^5.0.1
  fluttertoast: ^8.2.2
  shared_preferences: ^2.2.0
  sqflite_common_ffi: ^2.3.0  

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4
  build_runner: ^2.4.8
  flutter_lints: ^2.0.2 

flutter:
  uses-material-design: true
